### ISSUE TITLE
No auto power-on on alarm or programmed power on

### ISSUE THREAD

**Issue by andrea-musci** [AndroPlus-org/android_kernel_xiaomi_sdm845#1]
Hi,
I noticed that with version 0.7 auto power-on is not working: if you set an alarm and power off, then the phone is supposed to power on automatically when alarm fires and the same should happen when you use the auto power on functionality. With androplus kernel 0.7 this doesn't happen.
Standard kernel can power on phone automatically (personally tested).

**Comment by AndroPlus-org** [comment]
Thanks for the heads up, setting 1 here should fix this issue. I'll change it on the weekend.
https://github.com/AndroPlus-org/android_kernel_xiaomi_sdm845/blob/perseus-p/arch/arm64/boot/dts/qcom/pm8998.dtsi#L128

**Comment by andrea-musci** [comment]
Great! I look forward for next release then!

**Comment by AndroPlus-org** [comment]
I included it in v09. Can you test it?
https://drive.google.com/open?id=1AG-m-GEYeV1GWuOsW2OrlxaWJe-nysi4

**Comment by andrea-musci** [comment]
Hi,
It works really good!
Thanks!

Andrea

Il giorno sab 2 feb 2019, 06:17 AndroPlus <notifications@github.com> ha
scritto:
